#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 The Misty Authors
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Assembles the Apple artifact the iOS and macOS shells link: an `.xcframework` holding
# the Rust core's static slices, plus a Swift package wrapping it together with the
# UniFFI-generated Swift API (SPEC §11.7.1, ROADMAP P7/P8).
#
# THIS is the part that genuinely requires macOS: `xcodebuild -create-xcframework` and
# the Apple SDKs ship only there. The Swift *language* leg does not — the generated
# bindings compile and run the §11.8.2 conformance flow under a Linux Swift toolchain
# (`../conformance/run-swift.sh`), which is why that gate runs on every pull request and
# this script runs on the macOS job.
#
# Layout of the result, under target/apple/:
#
#   Misty.xcframework/         the C/FFI layer: one static slice per platform
#   Sources/Misty/misty.swift  the generated Swift API layer (not inside the framework)
#   Package.swift              ties the two together for SwiftPM consumers
#
# The Swift file lives outside the xcframework on purpose: an xcframework carries
# compiled code and headers, not Swift source, and the generated API layer must be
# compiled into the consuming module so its `async` methods keep Swift's calling
# convention rather than being frozen into a binary interface.
#
# Usage: crates/misty-ffi/apple/build-xcframework.sh

set -euo pipefail

if [ "$(uname -s)" != "Darwin" ]; then
  echo "error: this script needs macOS — xcodebuild and the Apple SDKs live there." >&2
  echo "       For the Swift conformance leg on any platform, use" >&2
  echo "       crates/misty-ffi/conformance/run-swift.sh instead." >&2
  exit 1
fi

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/../../.." && pwd)"
out="$root/target/apple"
lib="libmisty_ffi.a"

# See the note in ../conformance/run-swift.sh: askama resolves the bindgen templates
# through a path relative to CARGO_MANIFEST_DIR, which a symlinked CARGO_HOME breaks.
if [ -L "${CARGO_HOME:-$HOME/.cargo}" ]; then
  CARGO_HOME="$(readlink -f "${CARGO_HOME:-$HOME/.cargo}")"
  export CARGO_HOME
fi

# iOS device, both simulator architectures, and both macOS architectures. Apple requires
# the simulator and the device to be *separate* xcframework slices even though both are
# arm64 — same architecture, different platform triple — which is the whole reason
# xcframework exists rather than one fat binary.
targets=(
  aarch64-apple-ios
  aarch64-apple-ios-sim
  x86_64-apple-ios
  aarch64-apple-darwin
  x86_64-apple-darwin
)

echo "==> building the static slices"
for target in "${targets[@]}"; do
  rustup target add "$target" >/dev/null
  cargo build --manifest-path "$root/Cargo.toml" -p misty-ffi --release --target "$target"
done

rm -rf "$out"
mkdir -p "$out/slices/ios-device" "$out/slices/ios-sim" "$out/slices/macos"

cp "$root/target/aarch64-apple-ios/release/$lib" "$out/slices/ios-device/$lib"
lipo -create \
  "$root/target/aarch64-apple-ios-sim/release/$lib" \
  "$root/target/x86_64-apple-ios/release/$lib" \
  -output "$out/slices/ios-sim/$lib"
lipo -create \
  "$root/target/aarch64-apple-darwin/release/$lib" \
  "$root/target/x86_64-apple-darwin/release/$lib" \
  -output "$out/slices/macos/$lib"

echo "==> generating the Swift bindings"
# Library mode, from a slice that was actually built: the metadata then comes out of the
# artifact that gets shipped, not from a hand-written UDL that could describe something
# else. UniFFI's metadata is architecture-agnostic, so any one slice describes them all.
bindings="$out/bindings"
cargo run --manifest-path "$root/Cargo.toml" -p misty-ffi --features cli \
  --bin uniffi-bindgen --release -- \
  generate --library "$root/target/aarch64-apple-darwin/release/$lib" \
  --language swift --out-dir "$bindings"

# Swift's C importer looks for `module.modulemap` on the header search path; UniFFI emits
# `<namespace>FFI.modulemap`. Renaming it is all that is needed on Apple platforms — the
# `use "Darwin"` line it carries is correct here.
mkdir -p "$out/Headers"
cp "$bindings/mistyFFI.h" "$out/Headers/"
cp "$bindings/mistyFFI.modulemap" "$out/Headers/module.modulemap"

echo "==> creating Misty.xcframework"
xcodebuild -create-xcframework \
  -library "$out/slices/ios-device/$lib" -headers "$out/Headers" \
  -library "$out/slices/ios-sim/$lib" -headers "$out/Headers" \
  -library "$out/slices/macos/$lib" -headers "$out/Headers" \
  -output "$out/Misty.xcframework"

echo "==> emitting the SwiftPM wrapper"
mkdir -p "$out/Sources/Misty"
cp "$bindings/misty.swift" "$out/Sources/Misty/misty.swift"

cat >"$out/Package.swift" <<'SWIFT'
// swift-tools-version:5.9
// SPDX-FileCopyrightText: 2026 The Misty Authors
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Generated by crates/misty-ffi/apple/build-xcframework.sh — do not edit by hand.
//
// `MistyFFI` is the binary C layer (the Rust core, one static slice per Apple platform);
// `Misty` is the UniFFI-generated Swift API compiled into the consumer. An app depends
// on `Misty` and never names `MistyFFI` directly.
import PackageDescription

let package = Package(
    name: "Misty",
    platforms: [.iOS(.v15), .macOS(.v12)],
    products: [
        .library(name: "Misty", targets: ["Misty"])
    ],
    targets: [
        .binaryTarget(name: "MistyFFI", path: "Misty.xcframework"),
        .target(name: "Misty", dependencies: ["MistyFFI"])
    ]
)
SWIFT

echo
echo "built $out/Misty.xcframework"
xcodebuild -version >/dev/null && ls "$out/Misty.xcframework"
