// SPDX-FileCopyrightText: 2026 The Misty Authors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Aegis Authenticator vaults, plain and encrypted.
//!
//! # The format
//!
//! ```json
//! { "version": 1,
//!   "header": { "slots": null, "params": null },
//!   "db": { "version": 3, "entries": [ … ], "groups": [ … ] } }
//! ```
//!
//! When the vault is encrypted, `db` is a base64 string and `header` carries the
//! key material:
//!
//! ```json
//! { "version": 1,
//!   "header": {
//!     "slots": [ { "type": 1, "uuid": "…", "key": "<hex>",
//!                  "key_params": { "nonce": "<hex>", "tag": "<hex>" },
//!                  "n": 32768, "r": 8, "p": 1, "salt": "<hex>" } ],
//!     "params": { "nonce": "<hex>", "tag": "<hex>" } },
//!   "db": "<base64>" }
//! ```
//!
//! Each slot holds the 256-bit master key, encrypted under a key scrypt derives
//! from one password. `db` is AES-256-GCM under the master key, with the nonce and
//! the tag in `header.params` — the tag is **not** appended to the ciphertext, which
//! is the detail an implementation from the outside gets wrong. The plaintext is
//! the `db` **object** on its own, not a whole vault file.
//!
//! Source: Aegis's `docs/vault.md` and `VaultFile.java` / `PasswordSlot.java` /
//! `CryptoUtils.java` in `beemdevelopment/Aegis`. Reproduced here rather than
//! guessed, and the encrypted fixture in `tests/fixtures/aegis/` is generated by
//! `tests/fixture_provenance.rs` so the shape is checked rather than asserted.
//!
//! # Deliberate strictness
//!
//! An unknown top-level `version` is refused. Aegis has written `1` since the
//! format existed; a `2` would mean a change this code has not seen, and reading a
//! credential file on the assumption that nothing important moved is exactly the
//! wrong bet. The `db.version` is *not* refused — 1, 2 and 3 differ only in how
//! groups are stored, and both spellings are handled.

use base64::Engine as _;
use serde_json::Value;
use zeroize::Zeroizing;

use crate::build::{self, OtpFields};
use crate::collect::Collector;
use crate::context::ImportContext;
use crate::error::{ImportError, Result, RowError};
use crate::importer::{Confidence, Importer};
use crate::interop;
use crate::json::{self, Rec};
use crate::model::{ImportedItem, SourceFormat};
use crate::outcome::{ImportReport, ImportWarning, RowId, SkipReason};
use crate::text;

/// The only vault version this reads.
const VAULT_VERSION: u64 = 1;

/// Aegis slot type for a password-derived key. Type 2 is a biometric slot, whose
/// key lives in the Android keystore and cannot leave the device.
const SLOT_TYPE_PASSWORD: u64 = 1;

/// How many password slots to try before giving up.
///
/// Each attempt is one scrypt run at the file's own cost parameters, so a vault
/// claiming a thousand slots would otherwise be a thousand key derivations.
const MAX_SLOTS_TRIED: usize = 8;

/// Reads Aegis Authenticator JSON vaults, encrypted or not.
#[derive(Debug, Clone, Copy, Default)]
pub struct AegisImporter;

impl Importer for AegisImporter {
    fn format(&self) -> SourceFormat {
        SourceFormat::Aegis
    }

    fn sniff(&self, input: &[u8]) -> Confidence {
        let head = text::sniff_text(input);
        if !text::starts_json_object(&head) {
            return Confidence::No;
        }
        // `header` next to `db` is Aegis's shape and nobody else's.
        if head.contains("\"db\"") && head.contains("\"header\"") {
            return Confidence::Certain;
        }
        if head.contains("\"db\"") && head.contains("\"entries\"") {
            return Confidence::Likely;
        }
        Confidence::No
    }

    /// Answered from the text rather than by parsing: `detect` calls this for
    /// every candidate importer, and a full parse of a 30 MB vault to answer "will
    /// you need a password?" is a cost the UI should not pay. [`Importer::import`]
    /// makes the authoritative decision.
    fn needs_passphrase(&self, input: &[u8]) -> bool {
        let head = text::sniff_text(input);
        head.split_once("\"db\"")
            .and_then(|(_, rest)| rest.split_once(':'))
            .and_then(|(_, rest)| rest.chars().find(|ch| !ch.is_whitespace()))
            == Some('"')
    }

    fn import(&self, input: &[u8], ctx: &ImportContext<'_>) -> Result<ImportReport> {
        let doc = json::parse(input, ctx.limits())?;
        let root =
            Rec::object(&doc, SourceFormat::Aegis).map_err(|_| ImportError::UnrecognizedFormat)?;

        match root
            .u64("version")
            .map_err(|_| ImportError::InvalidField("version"))?
        {
            Some(VAULT_VERSION) => {}
            Some(other) => {
                return Err(ImportError::UnsupportedVersion {
                    format: SourceFormat::Aegis,
                    version: other,
                })
            }
            None => return Err(ImportError::MissingField("version")),
        }

        let db = root
            .at("db")
            .ok_or(ImportError::MissingField("db"))?
            .value();

        match db {
            Value::String(encoded) => {
                let plaintext = decrypt_db(&root, encoded, ctx)?;
                let inner: Value =
                    serde_json::from_slice(&plaintext).map_err(|error| ImportError::Json {
                        line: error.line(),
                        column: error.column(),
                    })?;
                read_db(&inner, ctx)
            }
            Value::Object(_) => read_db(db, ctx),
            _ => Err(ImportError::InvalidField("db")),
        }
    }
}

/// Derive the master key from one of the password slots and open `db`.
fn decrypt_db(
    root: &Rec<'_>,
    encoded_db: &str,
    ctx: &ImportContext<'_>,
) -> Result<Zeroizing<Vec<u8>>> {
    let passphrase = ctx
        .passphrase()
        .ok_or(ImportError::PassphraseRequired(SourceFormat::Aegis))?;

    let slots = root
        .array("header.slots")
        .ok_or(ImportError::MissingField("header.slots"))?;
    let params = root
        .at("header.params")
        .ok_or(ImportError::MissingField("header.params"))?;
    let nonce = hex_field(&params, "nonce", interop::NONCE_LEN, "header.params.nonce")?;
    let tag = hex_field(&params, "tag", interop::TAG_LEN, "header.params.tag")?;

    let ciphertext = base64::engine::general_purpose::STANDARD
        .decode(encoded_db.trim())
        .map_err(|_| ImportError::Base64("db"))?;

    let mut tried = 0usize;
    let mut last = ImportError::DecryptionFailed;
    for slot in slots {
        let slot = Rec::raw(slot, SourceFormat::Aegis);
        if slot.u64("type").ok().flatten() != Some(SLOT_TYPE_PASSWORD) {
            continue;
        }
        if tried >= MAX_SLOTS_TRIED {
            break;
        }
        tried += 1;

        match master_key_from_slot(&slot, passphrase, ctx) {
            Ok(master) => match interop::aes256gcm_open_split(&master, &nonce, &ciphertext, &tag) {
                Ok(plaintext) => return Ok(plaintext),
                Err(error) => last = error,
            },
            // A hostile KDF parameter is worth reporting even though another slot
            // might have worked: it names a specific, diagnosable problem, where
            // "wrong passphrase" does not.
            Err(error @ ImportError::KdfParam { .. }) => return Err(error),
            Err(error) => last = error,
        }
    }

    if tried == 0 {
        // Only biometric slots: the key is in the Android keystore of the device
        // that wrote the file, and no passphrase can substitute for it.
        return Err(ImportError::MissingField("header.slots[type=1]"));
    }
    Err(last)
}

/// Unwrap the 256-bit master key from one password slot.
fn master_key_from_slot(
    slot: &Rec<'_>,
    passphrase: &[u8],
    ctx: &ImportContext<'_>,
) -> Result<[u8; interop::KEY_LEN]> {
    let salt = hex_bytes(
        slot.str("salt")
            .ok_or(ImportError::MissingField("slot.salt"))?,
    )
    .ok_or(ImportError::Hex("slot.salt"))?;
    let n = slot
        .u64("n")
        .map_err(|_| ImportError::InvalidField("slot.n"))?
        .ok_or(ImportError::MissingField("slot.n"))?;
    let r = slot
        .u64("r")
        .map_err(|_| ImportError::InvalidField("slot.r"))?
        .ok_or(ImportError::MissingField("slot.r"))?;
    let p = slot
        .u64("p")
        .map_err(|_| ImportError::InvalidField("slot.p"))?
        .ok_or(ImportError::MissingField("slot.p"))?;
    let r = u32::try_from(r).map_err(|_| ImportError::KdfParam {
        name: "r",
        value: r,
    })?;
    let p = u32::try_from(p).map_err(|_| ImportError::KdfParam {
        name: "p",
        value: p,
    })?;

    let derived = interop::scrypt_key(passphrase, &salt, n, r, p, ctx.limits())?;

    let wrapped = hex_bytes(
        slot.str("key")
            .ok_or(ImportError::MissingField("slot.key"))?,
    )
    .ok_or(ImportError::Hex("slot.key"))?;
    let key_params = slot
        .at("key_params")
        .ok_or(ImportError::MissingField("slot.key_params"))?;
    let nonce = hex_field(
        &key_params,
        "nonce",
        interop::NONCE_LEN,
        "slot.key_params.nonce",
    )?;
    let tag = hex_field(&key_params, "tag", interop::TAG_LEN, "slot.key_params.tag")?;

    let master = interop::aes256gcm_open_split(&derived, &nonce, &wrapped, &tag)?;
    let mut key = [0u8; interop::KEY_LEN];
    if master.len() != key.len() {
        return Err(ImportError::DecryptionFailed);
    }
    key.copy_from_slice(&master);
    Ok(key)
}

fn hex_bytes(text: &str) -> Option<Vec<u8>> {
    hex::decode(text.trim()).ok()
}

fn hex_field(rec: &Rec<'_>, key: &str, len: usize, name: &'static str) -> Result<Vec<u8>> {
    let bytes = rec
        .str(key)
        .and_then(hex_bytes)
        .ok_or(ImportError::Hex(name))?;
    if bytes.len() == len {
        Ok(bytes)
    } else {
        Err(ImportError::Hex(name))
    }
}

/// Read the decrypted (or never-encrypted) `db` object.
fn read_db(db: &Value, ctx: &ImportContext<'_>) -> Result<ImportReport> {
    let db = Rec::object(db, SourceFormat::Aegis).map_err(|_| ImportError::InvalidField("db"))?;
    let entries = db
        .array("entries")
        .ok_or(ImportError::MissingField("db.entries"))?;

    // db v3 stores group UUIDs on the entry and the names in a top-level list;
    // v2 stored the name on the entry. Both are read.
    let group_names: Vec<(&str, &str)> = db
        .array("groups")
        .map(|groups| {
            groups
                .iter()
                .filter_map(|group| {
                    let group = Rec::raw(group, SourceFormat::Aegis);
                    Some((group.str("uuid")?, group.str("name")?))
                })
                .collect()
        })
        .unwrap_or_default();

    let mut collector = Collector::new(SourceFormat::Aegis, ctx);
    for entry in entries {
        if collector.is_full() {
            return Err(ImportError::TooManyRows {
                max: ctx.limits().max_rows,
            });
        }
        let row = RowId::at(collector.rows());
        match read_entry(entry, &group_names, ctx) {
            Ok(Some((item, warnings))) => {
                let row = row.labelled(item.issuer.as_deref(), &item.account);
                collector.accept(row, item, warnings);
            }
            Ok(None) => collector.skip(
                row,
                SkipReason::UnsupportedType(
                    Rec::raw(entry, SourceFormat::Aegis)
                        .text("type")
                        .unwrap_or_default(),
                ),
            ),
            Err(error) => collector.fail(row, error),
        }
    }
    Ok(collector.finish())
}

type EntryResult = core::result::Result<Option<(ImportedItem, Vec<ImportWarning>)>, RowError>;

fn read_entry(entry: &Value, groups: &[(&str, &str)], ctx: &ImportContext<'_>) -> EntryResult {
    let entry = Rec::object(entry, SourceFormat::Aegis)?;
    let Some(kind) = build::kind_from_str(entry.require_str("type")?) else {
        return Ok(None);
    };
    let info = entry.at("info").ok_or(RowError::MissingField("info"))?;

    let (config, mut warnings) = build::config(&OtpFields {
        default_kind: kind,
        secret: Some(info.require_str("secret")?),
        algorithm: info.str("algo"),
        digits: info.u8("digits")?,
        period: info.u16("period")?,
        counter: info.u64("counter")?,
        pin: info.str("pin"),
        ..OtpFields::default()
    })?;

    let mut item = ImportedItem::new(
        SourceFormat::Aegis,
        config,
        entry.str("issuer").map(str::to_owned),
        entry.str("name").unwrap_or_default().to_owned(),
    );
    item.note = text::non_empty(entry.str("note"));
    item.favorite = entry.bool("favorite").unwrap_or(false);
    item.groups = entry_groups(&entry, groups, ctx);

    // Aegis embeds the icon as base64 image bytes. Misty has nowhere to put a
    // bitmap, and re-encoding somebody's PNG into a vault item is not this crate's
    // business, so it is dropped out loud.
    if entry.str("icon").is_some() {
        warnings.push(ImportWarning::DroppedField("icon"));
    }

    Ok(Some((item, warnings)))
}

fn entry_groups(entry: &Rec<'_>, groups: &[(&str, &str)], ctx: &ImportContext<'_>) -> Vec<String> {
    if let Some(uuids) = entry.array("groups") {
        return uuids
            .iter()
            .filter_map(Value::as_str)
            .filter_map(|uuid| {
                groups
                    .iter()
                    .find(|(id, _)| *id == uuid)
                    .map(|(_, name)| (*name).to_owned())
            })
            .take(ctx.limits().max_tags)
            .collect();
    }
    entry.str("group").map(str::to_owned).into_iter().collect()
}
