// SPDX-FileCopyrightText: 2026 The Misty Authors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Device-to-device enrollment (SPEC §6.3).
//!
//! ```text
//! 1. the new device generates its identity plus an ephemeral X25519 pair and
//!    shows a QR of {enroll_id, device_id, x25519_pub, ed25519_pub, name,
//!    platform} plus a 6-digit code derived from that payload;
//! 2. an existing device scans it (or the user types the 6-digit code), MUST
//!    display the new device's name, platform and code for out-of-band
//!    comparison, and only then approves;
//! 3. on approval the existing device does X25519 + HKDF, seals
//!    {vault_id, VK, epoch, server_url, roster} to the new device, adds it to
//!    the roster, signs the roster and pushes both;
//! 4. the new device unseals, checks that the approver is in the delivered
//!    roster, that the roster's own signature verifies, and that it is itself
//!    in the roster under its own key.
//! ```
//!
//! This is the `A6` mitigation in its active form: the server can hand a new
//! device any blob it likes, and without an approving device's X25519 half and
//! Ed25519 signature none of it opens or verifies.
//!
//! # Deviation from SPEC §6.3
//!
//! [`EnrollmentRequest`] carries `device_id` in addition to the five fields
//! §6.3.1 lists. The roster record in §6.2 requires a `device_id`, ids are
//! generated by the device that owns them (§3), and nothing else in the flow
//! supplies one — so either the QR carries it or the approver has to invent an
//! id for someone else's device. It is covered by the confirmation code, so it
//! cannot be substituted in transit without the code changing.

use core::fmt;

use blake2::digest::consts::U32;
use blake2::{Blake2b, Digest};
use serde::{Deserialize, Serialize};
use x25519_dalek::{PublicKey, StaticSecret};
use zeroize::{Zeroize, Zeroizing};

use crate::identity::{DeviceIdentity, Roster, MAX_NAME_LEN, MAX_PLATFORM_LEN};
use crate::keys::{VaultKey, KEY_LEN};
use crate::{aead, derive, random, DeviceId, EnrollId, Error, Result, SignatureBytes, VaultId};

/// BLAKE2b with a 256-bit output, the internal hash of SPEC §2.1.
type Blake2b256 = Blake2b<U32>;

/// Digits in the out-of-band confirmation code.
pub const CONFIRMATION_CODE_DIGITS: u32 = 6;

/// Domain separator for the confirmation code and the request encoding.
pub const REQUEST_CONTEXT: &[u8] = b"misty/enroll-request/v1";

/// Domain separator for the sealed grant's AAD and signature.
pub const SEAL_CONTEXT: &[u8] = b"misty/enroll-seal/v1";

/// Longest `server_url` accepted in a grant.
pub const MAX_SERVER_URL_LEN: usize = 512;

/// What the new device publishes in its QR (and behind the 6-digit code).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct EnrollmentRequest {
    /// Identifies this enrollment attempt on the server.
    pub enroll_id: EnrollId,
    /// The new device's id, which the approver will put in the roster.
    pub device_id: DeviceId,
    /// Ephemeral X25519 public key, used only for this enrollment.
    pub x25519_pub: [u8; 32],
    /// The new device's long-lived Ed25519 public key.
    pub ed25519_pub: [u8; 32],
    /// Name to show the approving user.
    pub name: String,
    /// Platform to show the approving user.
    pub platform: String,
}

impl EnrollmentRequest {
    /// The exact bytes the confirmation code is computed over:
    ///
    /// ```text
    /// "misty/enroll-request/v1"
    /// enroll_id[16] || device_id[16] || x25519_pub[32] || ed25519_pub[32]
    /// LE32(name_len)     || name
    /// LE32(platform_len) || platform
    /// ```
    #[must_use]
    pub fn canonical_bytes(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(REQUEST_CONTEXT.len() + 128);
        out.extend_from_slice(REQUEST_CONTEXT);
        out.extend_from_slice(self.enroll_id.as_bytes());
        out.extend_from_slice(self.device_id.as_bytes());
        out.extend_from_slice(&self.x25519_pub);
        out.extend_from_slice(&self.ed25519_pub);
        for field in [&self.name, &self.platform] {
            let bytes = field.as_bytes();
            out.extend_from_slice(&u32::try_from(bytes.len()).unwrap_or(u32::MAX).to_le_bytes());
            out.extend_from_slice(bytes);
        }
        out
    }

    /// The 6-digit code the two users compare out of band.
    ///
    /// `BLAKE2b-256(canonical_bytes)`, first four bytes as a big-endian `u32`,
    /// modulo 10^6, zero-padded. The modulo biases the first 4294 values by
    /// about one part in a million, which is irrelevant for a code a human
    /// reads aloud, and the code is a *comparison* device — the security of the
    /// exchange rests on X25519 and Ed25519, not on these 20 bits.
    #[must_use]
    pub fn confirmation_code(&self) -> String {
        let digest = Blake2b256::digest(self.canonical_bytes());
        let mut head = [0u8; 4];
        if let Some(slice) = digest.get(..4) {
            head.copy_from_slice(slice);
        }
        let modulus = 10u32.pow(CONFIRMATION_CODE_DIGITS);
        let value = u32::from_be_bytes(head) % modulus;
        format!("{value:0width$}", width = CONFIRMATION_CODE_DIGITS as usize)
    }

    /// Bounds the user-supplied strings.
    ///
    /// # Errors
    ///
    /// [`Error::StringTooLong`].
    pub fn validate(&self) -> Result<()> {
        if self.name.len() > MAX_NAME_LEN {
            return Err(Error::StringTooLong {
                field: "device name",
                max: MAX_NAME_LEN,
            });
        }
        if self.platform.len() > MAX_PLATFORM_LEN {
            return Err(Error::StringTooLong {
                field: "device platform",
                max: MAX_PLATFORM_LEN,
            });
        }
        Ok(())
    }
}
/// The sealed grant an approving device sends back.
///
/// Everything here is public: the ciphertext is the only secret, and it is
/// bound to this `enroll_id` and to both X25519 public keys.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SealedEnrollment {
    /// Which enrollment this answers.
    pub enroll_id: EnrollId,
    /// Which device approved.
    pub approver_device_id: DeviceId,
    /// The approver's ephemeral X25519 public key.
    pub approver_x25519_pub: [u8; 32],
    /// The new device's X25519 public key, echoed back so the AAD is explicit.
    pub new_device_x25519_pub: [u8; 32],
    /// AEAD nonce.
    pub nonce: [u8; aead::NONCE_LEN],
    /// The sealed grant.
    pub ciphertext: Vec<u8>,
    /// The approver's Ed25519 signature over the AAD followed by the
    /// ciphertext.
    pub signature: SignatureBytes,
}

impl SealedEnrollment {
    /// `SEAL_CONTEXT || enroll_id || approver_device_id ||
    /// approver_x25519_pub || new_device_x25519_pub || nonce`.
    fn aad(&self) -> Vec<u8> {
        seal_aad(
            &self.enroll_id,
            &self.approver_device_id,
            &self.approver_x25519_pub,
            &self.new_device_x25519_pub,
            &self.nonce,
        )
    }

    fn signed_message(&self) -> Vec<u8> {
        let mut message = self.aad();
        message.extend_from_slice(&self.ciphertext);
        message
    }
}

fn seal_aad(
    enroll_id: &EnrollId,
    approver_device_id: &DeviceId,
    approver_x25519_pub: &[u8; 32],
    new_device_x25519_pub: &[u8; 32],
    nonce: &[u8; aead::NONCE_LEN],
) -> Vec<u8> {
    let mut out = Vec::with_capacity(SEAL_CONTEXT.len() + 120);
    out.extend_from_slice(SEAL_CONTEXT);
    out.extend_from_slice(enroll_id.as_bytes());
    out.extend_from_slice(approver_device_id.as_bytes());
    out.extend_from_slice(approver_x25519_pub);
    out.extend_from_slice(new_device_x25519_pub);
    out.extend_from_slice(nonce);
    out
}

/// What an approving device hands over.
#[derive(Debug)]
pub struct GrantContents<'a> {
    /// The vault's server-side address.
    pub vault_id: VaultId,
    /// The vault key. Borrowed, never copied except into the sealed CBOR.
    pub vault_key: &'a VaultKey,
    /// The current epoch.
    pub epoch: u32,
    /// Where the vault syncs.
    pub server_url: &'a str,
    /// The roster, already containing the new device and re-signed.
    pub roster: &'a Roster,
}

/// What the new device gets out.
///
/// `Debug` shows everything except the vault key, which renders `[redacted]`
/// through its own `Debug`.
#[derive(Debug)]
pub struct EnrollmentGrant {
    /// The vault's server-side address.
    pub vault_id: VaultId,
    /// The vault key. Zeroized on drop.
    pub vault_key: VaultKey,
    /// The current epoch.
    pub epoch: u32,
    /// Where the vault syncs.
    pub server_url: String,
    /// The verified roster, including this device.
    pub roster: Roster,
}

/// The wire form of a grant.
///
/// Private, and the only place a [`VaultKey`] is ever serialised — this is the
/// "explicit sealing API" the key types' missing `Serialize` points at.
#[derive(Serialize, Deserialize)]
struct GrantWire {
    vault_id: VaultId,
    vault_key: [u8; KEY_LEN],
    epoch: u32,
    server_url: String,
    roster: Roster,
}
/// The new device's side of an enrollment: the request plus the ephemeral
/// X25519 private key that will open the answer.
///
/// `Debug` renders the request and `[redacted]` for the private key.
pub struct NewDeviceEnrollment {
    request: EnrollmentRequest,
    ephemeral: StaticSecret,
}

impl NewDeviceEnrollment {
    /// Starts an enrollment for `identity`.
    ///
    /// # Errors
    ///
    /// [`Error::Random`], or [`Error::StringTooLong`] if
    /// `name` or `platform` is over its bound.
    pub fn begin(identity: &DeviceIdentity, name: &str, platform: &str) -> Result<Self> {
        let ephemeral = StaticSecret::from(random::array::<32>()?);
        let request = EnrollmentRequest {
            enroll_id: EnrollId::generate()?,
            device_id: identity.device_id(),
            x25519_pub: PublicKey::from(&ephemeral).to_bytes(),
            ed25519_pub: identity.ed25519_public(),
            name: name.to_owned(),
            platform: platform.to_owned(),
        };
        request.validate()?;
        Ok(Self { request, ephemeral })
    }

    /// The request to render as a QR.
    #[must_use]
    pub const fn request(&self) -> &EnrollmentRequest {
        &self.request
    }

    /// The 6-digit code to display next to the QR.
    #[must_use]
    pub fn confirmation_code(&self) -> String {
        self.request.confirmation_code()
    }

    /// Unseals an approver's answer and checks that it chains to a device the
    /// roster vouches for.
    ///
    /// Order: `enroll_id` match, AEAD, CBOR, roster shape, approver present in
    /// the delivered roster, approver's signature, the roster's own signature,
    /// and finally that *this* device is in the roster under its own Ed25519
    /// key. A grant that fails any of these is not partially applied — nothing
    /// is returned at all.
    ///
    /// # Errors
    ///
    /// [`Error::EnrollIdMismatch`], [`Error::NonContributoryKeyExchange`],
    /// [`Error::EnrollmentUnsealFailed`], [`Error::Cbor`],
    /// [`Error::EnrollmentApproverUnknown`],
    /// [`Error::EnrollmentSignatureInvalid`], [`Error::RosterUnsigned`],
    /// [`Error::RosterSignatureInvalid`], [`Error::DeviceNotInRoster`], or
    /// [`Error::StringTooLong`].
    pub fn open(&self, sealed: &SealedEnrollment) -> Result<EnrollmentGrant> {
        if sealed.enroll_id != self.request.enroll_id {
            return Err(Error::EnrollIdMismatch);
        }
        if sealed.new_device_x25519_pub != self.request.x25519_pub {
            return Err(Error::EnrollmentUnsealFailed);
        }
        let shared = self
            .ephemeral
            .diffie_hellman(&PublicKey::from(sealed.approver_x25519_pub));
        if !shared.was_contributory() {
            return Err(Error::NonContributoryKeyExchange);
        }
        let key = derive::enrollment_sealing_key(
            &shared.to_bytes(),
            &sealed.enroll_id,
            &sealed.approver_x25519_pub,
            &self.request.x25519_pub,
        )?;
        let plaintext = aead::decrypt(
            key.expose_secret(),
            &sealed.nonce,
            &sealed.aad(),
            &sealed.ciphertext,
            Error::EnrollmentUnsealFailed,
        )?;
        let mut wire: GrantWire =
            ciborium::from_reader(plaintext.as_slice()).map_err(|error| Error::Cbor {
                operation: "decode",
                detail: error.to_string(),
            })?;
        if wire.server_url.len() > MAX_SERVER_URL_LEN {
            return Err(Error::StringTooLong {
                field: "server_url",
                max: MAX_SERVER_URL_LEN,
            });
        }
        wire.roster.validate()?;

        // The approver must be in the roster it delivered...
        let approver = wire
            .roster
            .contains(&sealed.approver_device_id)
            .ok_or(Error::EnrollmentApproverUnknown)?;
        approver
            .verifying_key()?
            .verify_strict(
                &sealed.signed_message(),
                &ed25519_dalek::Signature::from_bytes(sealed.signature.as_bytes()),
            )
            .map_err(|_| Error::EnrollmentSignatureInvalid)?;

        // ...the roster must be signed by one of its own members...
        wire.roster.verify()?;

        // ...and this device must actually be in it, under its own key.
        let own =
            wire.roster
                .contains(&self.request.device_id)
                .ok_or(Error::DeviceNotInRoster {
                    device: self.request.device_id,
                })?;
        if own.ed25519_pub != self.request.ed25519_pub {
            return Err(Error::DeviceNotInRoster {
                device: self.request.device_id,
            });
        }

        let vault_key = VaultKey::from_bytes(wire.vault_key);
        wire.vault_key.zeroize();
        Ok(EnrollmentGrant {
            vault_id: wire.vault_id,
            vault_key,
            epoch: wire.epoch,
            server_url: wire.server_url,
            roster: wire.roster,
        })
    }
}

impl fmt::Debug for NewDeviceEnrollment {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "NewDeviceEnrollment {{ request: {:?}, ephemeral: [redacted] }}",
            self.request
        )
    }
}
/// Approves an enrollment and seals the grant to the new device.
///
/// `confirmation_code` is what the *user* read off the new device and typed or
/// confirmed here. It is checked against the request before anything is sealed,
/// so a substituted QR payload — a different `x25519_pub`, a different
/// `device_id` — cannot be approved by a user who compared the code.
///
/// `grant.roster` must already contain the new device and be re-signed by the
/// approver; [`Roster::add`](crate::identity::Roster::add) then
/// [`Roster::sign`](crate::identity::Roster::sign) does that. This function
/// checks it, because a grant delivering a roster the new device is not in
/// would leave it permanently unable to write.
///
/// # Errors
///
/// [`Error::ConfirmationCodeMismatch`], [`Error::DeviceNotInRoster`],
/// [`Error::NonContributoryKeyExchange`], [`Error::Cbor`],
/// [`Error::Random`], [`Error::StringTooLong`], or
/// anything [`Roster::verify`](crate::identity::Roster::verify) rejects.
pub fn approve(
    request: &EnrollmentRequest,
    confirmation_code: &str,
    grant: &GrantContents<'_>,
    approver: &DeviceIdentity,
) -> Result<SealedEnrollment> {
    request.validate()?;
    if !bool::from(constant_time_code_eq(
        confirmation_code.trim(),
        &request.confirmation_code(),
    )) {
        return Err(Error::ConfirmationCodeMismatch);
    }
    if grant.server_url.len() > MAX_SERVER_URL_LEN {
        return Err(Error::StringTooLong {
            field: "server_url",
            max: MAX_SERVER_URL_LEN,
        });
    }
    // The roster we are about to hand over must be valid, signed by the
    // approver, and must already include the device being enrolled.
    let signer = grant.roster.verify()?;
    if signer.device_id != approver.device_id() {
        return Err(Error::RosterSignerNotInRoster {
            signer: approver.device_id(),
        });
    }
    let enrolled = grant
        .roster
        .contains(&request.device_id)
        .ok_or(Error::DeviceNotInRoster {
            device: request.device_id,
        })?;
    if enrolled.ed25519_pub != request.ed25519_pub {
        return Err(Error::DeviceNotInRoster {
            device: request.device_id,
        });
    }

    let ephemeral = StaticSecret::from(random::array::<32>()?);
    let approver_x25519_pub = PublicKey::from(&ephemeral).to_bytes();
    let shared = ephemeral.diffie_hellman(&PublicKey::from(request.x25519_pub));
    if !shared.was_contributory() {
        return Err(Error::NonContributoryKeyExchange);
    }
    let key = derive::enrollment_sealing_key(
        &shared.to_bytes(),
        &request.enroll_id,
        &approver_x25519_pub,
        &request.x25519_pub,
    )?;

    let wire = GrantWire {
        vault_id: grant.vault_id,
        vault_key: *grant.vault_key.expose_secret(),
        epoch: grant.epoch,
        server_url: grant.server_url.to_owned(),
        roster: grant.roster.clone(),
    };
    let mut encoded = Zeroizing::new(Vec::new());
    let encode_result = ciborium::into_writer(&wire, &mut *encoded).map_err(|error| Error::Cbor {
        operation: "encode",
        detail: error.to_string(),
    });
    // `wire` holds a copy of the vault key; wipe it whether or not encoding
    // succeeded.
    let mut wire = wire;
    wire.vault_key.zeroize();
    encode_result?;

    let nonce = random::array::<{ aead::NONCE_LEN }>()?;
    let aad = seal_aad(
        &request.enroll_id,
        &approver.device_id(),
        &approver_x25519_pub,
        &request.x25519_pub,
        &nonce,
    );
    let ciphertext = aead::encrypt(key.expose_secret(), &nonce, &aad, &encoded)?;

    let mut message = aad;
    message.extend_from_slice(&ciphertext);
    Ok(SealedEnrollment {
        enroll_id: request.enroll_id,
        approver_device_id: approver.device_id(),
        approver_x25519_pub,
        new_device_x25519_pub: request.x25519_pub,
        nonce,
        ciphertext,
        signature: approver.sign(&message),
    })
}

/// Compares two confirmation codes without leaking where they differ.
///
/// Overkill for six digits a human just read aloud, but the habit is cheap and
/// the alternative is a `==` on attacker-influenced material.
fn constant_time_code_eq(left: &str, right: &str) -> subtle::Choice {
    use subtle::ConstantTimeEq;
    if left.len() != right.len() {
        return subtle::Choice::from(0u8);
    }
    left.as_bytes().ct_eq(right.as_bytes())
}
